// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.44
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace KeyboardHero
{
    internal sealed partial class Vsix
    {
        public const string Id = "KeyboardHero.a180ac1b-e008-4a04-8d2b-30266ce0e9a6";
        public const string Name = "Keyboard Hero";
        public const string Description = @"Shows you what keyboard shortcuts you would benefit the most from learning based on your usage of Visual Studio";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "";
        public const bool IsPreview = false;
    }
}
