// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.44
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace KeyboardHero
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string KeyboardHeroString = "bdd2cfc9-9e09-4690-b761-88b2b42a4cd4";
        public static Guid KeyboardHero = new Guid(KeyboardHeroString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int Toolbar = 0x0001;
        public const int ToolbarCommandGroup = 0x0010;
        public const int ToolbarUtilityGroup = 0x0020;
        public const int ShowHistoryWindow = 0x0100;
        public const int Toggle = 0x0150;
        public const int ReloadWindow = 0x0200;
        public const int Reset = 0x0300;
        public const int OpenIgnoreList = 0x0400;
        public const int OpenCommandList = 0x0500;
    }
}
